server:
  port: 8082
spring:
  application:
    name: empresa-api

  cloud:
    openfeign:
      client:
        config:
          viaCepClient:
            connectTimeout: 3000
            readTimeout: 500
            loggerLevel: BASIC
  sql:
    init:
      continue-on-error: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/postgres}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:senha123}
    hikari:
      connection-timeout: 200000
      maximum-pool-size: 5
      idle-timeout: 300000
      max-lifetime: 300000
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://172.23.0.1:8761/eureka/
url:
  viacep.host: https://viacep.com.br/ws