server:
  port: 8082
spring:
  application:
    name: empresa-app
  sql:
    init:
      continue-on-error: true
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: admin
    password: senha123
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect