server:
  port: 8082
spring:
  application:
    name: empresa-app
  sql:
    init:
      continue-on-error: true
  datasource:
    url: jdbc:postgresql://postgres-ethos.postgres.database.azure.com:5432/postgres
    username: postgres
    password: Senha123
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect