server:
  port: 8082
spring:
  application:
    name: empresa-app

  cloud:
    openfeign:
      client:
        config:
          viaCepClient:
            connectTimeout: 3000
            readTimeout: 500
            loggerLevel: BASIC
  sql:
    init:
      continue-on-error: true
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: admin
    password: senha123

    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

url:
  viacep.host: https://viacep.com.br/ws