name: Deploy to EC2
on:
  workflow_run:
    workflows: [ "Docker Image CI" ]
    types:
      - completed
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: deploy na ec2 privada
        run: |
          ssh -t -i /home/ubuntu/.ssh/ethos.pem -o StrictHostKeyChecking=no ubuntu@10.0.0.171
            cd docker-compose-ethos
            docker-compose -f stack.yaml pull
            docker-compose -f stack.yaml up -d
